name = "CornerSpaceRenorm"
uuid = "a416d433-5cba-5b7c-a8b4-92be737addfd"
authors = ["Z-Denis <zakari.denis@univ-paris-diderot.fr>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
